apiVersion: apps/v1
kind: Deployment
metadata:
  name: lanchonete-orchestrator
  namespace: app
spec:
  replicas: 1
  selector:
    matchLabels: { app: lanchonete-orchestrator }
  template:
    metadata:
      labels: { app: lanchonete-orchestrator }
    spec:
      containers:
        - name: orchestrator
          image: "${IMAGE_URI}"
          imagePullPolicy: Always
          env:
            - name: SERVICE_PRODUCTION_URL
              value: "${SERVICE_PRODUCTION_URL}"

            - name: SERVICE_ORDER_URL
              value: "${SERVICE_ORDER_URL}"

            - name: SERVICE_PAYMENT_URL
              value: "${SERVICE_PAYMENT_URL}"

            - name: REQUEST_TIMEOUT
              value: "${REQUEST_TIMEOUT}"
          ports:
            - containerPort: 8080
          command: ["python"]
          args: ["-m", "uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8080"]
          resources:
            requests:
              memory: "300Mi"
              cpu: "200m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          readinessProbe:
            httpGet: { path: /health, port: 8080 }
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet: { path: /health, port: 8080 }
            initialDelaySeconds: 20
            periodSeconds: 20