apiVersion: v1
kind: Service
metadata:
  name: lanchonete-orchestrator
  namespace: app
spec:
  type: ClusterIP
  selector:
    app: lanchonete-orchestrator
  ports:
    - name: http
      port: 80        # porta exposta dentro do cluster
      targetPort: 8080  # porta do container (a mesma do Deployment)