apiVersion: v1
kind: Service
metadata:
  name: lanchonete-orchestrator-lb
  namespace: app
spec:
  type: LoadBalancer
  selector:
    app: lanchonete-orchestrator
  ports:
    - name: http
      port: 80          # porta exposta externamente (LoadBalancer)
      targetPort: 8080  # porta real do container (uvicorn)